sonar.projectKey=owasp-juice-shopsonar.projectName=owasp-juice-shopsonar.projectVersion=1.0sonar.sources=.sonar.sourceEncoding=UTF-8sonar.host.url=http://localhost:9000sonar.login=sqp_dd3d9b51743e36b90e7aacaae6120ef29e86fa88

